# Define the top words for each CV category
cv_categories = {
    "Advocate": ["details", "legal", "law", "university", "advocate", "exprience", "january", "company", "court", "maharashtra", "description", "skill", "less", "year", "months", "district", "mumbai", "pune", "llb", "college", "courts", "cases", "chennai", "high", "criminal", "matters", "paper", "education", "monthscompany", "2008", "india", "2012", "work", "drafting", "practice", "skills", "civil", "working", "authority", "litigation"],
    "Arts": ["ã", "company", "arts", "details", "description", "january", "maharashtra", "india", "college", "skill", "british", "music", "days", "development", "events", "council", "responsibilities", "projects", "mumbai", "pune", "university", "experience", "state", "managing", "new", "marketing", "management", "nagpur", "workshop", "team", "board", "programmes", "programme", "sri", "lanka", "media", "communication", "international", "business", "commerce"],
    "Automation Testing": ["test", "testing", "automation", "company", "description", "qtp", "project", "exprience", "months", "using", "details", "good", "system", "team", "integration", "involved", "software", "cases", "selenium", "environment", "sql", "manual", "regression", "knowledge", "c", "development", "creation", "responsibilities", "design", "qa", "maharashtra", "functional", "web", "release", "case", "plan", "python", "documents", "scripts", "application"],
    "Blockchain": ["company", "blockchain", "description", "exprience", "months", "details", "system", "ethereum", "january", "technology", "smart", "computer", "maharashtra", "mysql", "java", "2014", "2017", "engineering", "developer", "worked", "management", "build", "web", "c", "project", "skill", "global", "services", "contracts", "monthscompany", "product", "skills", "solidity", "based", "limited", "analytics", "used", "html", "javascript", "css"],
    "Business Analyst": ["business", "test", "company", "description", "testing", "management", "project", "details", "requirement", "requirements", "team", "exprience", "process", "functional", "months", "system", "analysis", "responsibilities", "analyst", "user", "various", "january", "maharashtra", "report", "client", "work", "ltd", "mumbai", "cases", "processes", "gathering", "pvt", "cash", "maintain", "application", "excel", "automation", "documentation", "uat", "ms"],
    "Civil Engineer": ["project", "civil", "engineer", "site", "company", "description", "construction", "details", "india", "inspection", "work", "qaqc", "exprience", "engineering", "mumbai", "client", "drawings", "maharashtra", "quality", "months", "material", "building", "name", "al", "etc", "subcontractors", "skill", "position", "responsibilities", "including", "job", "specifications", "materials", "ensure", "villas", "january", "autocad", "projects", "test", "contractor"],
    "Data Science": ["data", "exprience", "months", "learning", "python", "science", "year", "less", "machine", "details", "analytics", "ª", "using", "like", "analysis", "company", "deep", "description", "business", "project", "sap", "knowledge", "sql", "skills", "platform", "text", "development", "information", "technical", "nlp", "industry", "experience", "neural", "tableau", "engineering", "hana", "involved", "algorithms", "models", "developed"],
    "Database": ["â", "database", "sql", "server", "oracle", "exprience", "databases", "description", "using", "company", "ï", "details", "months", "backup", "installation", "servers", "issues", "management", "data", "ââ", "ltd", "support", "windows", "monitoring", "administrator", "log", "creating", "rman", "mysql", "backups", "linux", "user", "worked", "working", "responsibilities", "team", "production", "replication", "administration", "users"],
    "DevOps Engineer": ["exprience", "project", "months", "shell", "devops", "team", "company", "description", "servers", "build", "mysql", "automation", "applications", "scripts", "details", "less", "year", "users", "software", "cloud", "support", "scripting", "deployment", "development", "different", "technologies", "ecommerce", "engineer", "creating", "ltd", "pvt", "management", "aws", "application", "product", "git", "database", "linux", "nendrasys", "tasks"],
    "DotNet Developer": ["exprience", "months", "project", "net", "database", "sql", "server", "details", "developer", "description", "application", "management", "aspnet", "system", "less", "year", "jquery", "dot", "role", "mvc", "company", "javascript", "pune", "layer", "development", "environment", "web", "worked", "framework", "c", "visual", "html", "studio", "like", "comments", "css", "maharashtra", "software", "designing", "used"],
    "ETL Developer": ["data", "etl", "informatica", "sql", "exprience", "project", "details", "using", "talend", "developer", "months", "testing", "description", "company", "unix", "services", "mappings", "server", "environment", "business", "january", "unit", "jobs", "center", "source", "job", "maharashtra", "oracle", "development", "power", "files", "warehouse", "reconciliation", "system", "feeds", "documents", "developed", "database", "assurant", "knowledge"],
    "Electrical Engineering": ["electrical", "maintenance", "engineering", "power", "project", "details", "company", "ltd", "maharashtra", "description", "operation", "control", "plant", "pvt", "technical", "layout", "design", "equipment", "cable", "pune", "panels", "panel", "completed", "work", "management", "per", "drawing", "activities", "university", "process", "lt", "distribution", "installation", "autocad", "knowledge", "standards", "skill", "exprience", "line", "drawings"],
    "HR": ["details", "hr", "exprience", "company", "management", "description", "skill", "months", "education", "skills", "monthscompany", "payroll", "june", "january", "engineering", "university", "computer", "mba", "college", "software", "statutory", "compliance", "employee", "salary", "employees", "dynamics", "2017", "2014", "school", "payment", "form", "training", "accounting", "dbms", "tamil", "nadu", "less", "year", "ms", "office"],
    "Hadoop": ["data", "hadoop", "hive", "using", "description", "sqoop", "hdfs", "project", "exprience", "details", "company", "months", "cluster", "developer", "spark", "involved", "mapreduce", "pig", "queries", "system", "like", "tables", "used", "database", "various", "skill", "different", "scala", "environment", "hbase", "processing", "worked", "java", "ecosystem", "team", "developed", "testing", "map", "reduce", "services"],
    "Health and fitness": ["fitness", "company", "description", "details", "health", "gym", "skills", "nutrition", "management", "sales", "january", "responsibilities", "science", "related", "college", "training", "team", "handling", "queries", "customers", "education", "skill", "hotel", "university", "months", "work", "customer", "centre", "high", "good", "people", "spa", "perform", "duties", "assigned", "etc", "care", "club", "manager", "goqii"],
    "Java Developer": ["java", "exprience", "months", "developer", "details", "description", "company", "less", "year", "maharashtra", "technologies", "ajax", "spring", "jsp", "mysql", "hibernate", "january", "project", "technology", "javascript", "development", "skill", "pvt", "ltd", "j2ee", "system", "servlet", "c", "jquery", "web", "database", "education", "monthscompany", "windows", "computer", "software", "pune", "using", "title", "skills"],
    "Mechanical Engineer": ["engineering", "mechanical", "company", "design", "details", "description", "technical", "project", "products", "customer", "vendor", "ltd", "cost", "work", "training", "projects", "role", "sales", "vendors", "development", "machine", "exprience", "responsibilities", "process", "time", "pune", "manufacturing", "pvt", "order", "proposal", "mumbai", "maharashtra", "also", "quotations", "team", "ensure", "maintain", "supply", "engineer", "may"],
    "Network Security Engineer": ["network", "exprience", "security", "cisco", "months", "configuration", "year", "less", "management", "firewall", "etc", "description", "server", "company", "switches", "details", "project", "servers", "firewalls", "devices", "troubleshooting", "technologies", "client", "engineer", "troubleshoot", "ãâ", "asa", "maintaining", "maharashtra", "networking", "router", "implementation", "routers", "routing", "lan", "access", "dhcp", "based", "windows", "backup"],
    "Operations Manager": ["team", "company", "operations", "project", "services", "client", "management", "ensuring", "description", "system", "customer", "manager", "quality", "development", "work", "ltd", "business", "india", "job", "timely", "process", "ensure", "meetings", "ges", "control", "activities", "monitored", "honeywell", "customers", "managing", "activity", "international", "delivery", "engineering", "details", "various", "reports", "issues", "handling", "per"],
    "PMO": ["management", "ãâ", "project", "report", "responsible", "business", "reports", "exprience", "sla", "team", "data", "skills", "months", "company", "documentation", "description", "process", "resource", "monitor", "training", "senior", "maintain", "ensure", "risk", "reporting", "details", "pmo", "operations", "billing", "requirements", "delivery", "ability", "work", "time", "client", "pune", "new", "managers", "processes", "school"],
    "Python Developer": ["python", "exprience", "months", "pune", "completed", "details", "developer", "training", "year", "internal", "maharashtra", "less", "project", "development", "web", "mysql", "computer", "company", "technical", "django", "erp", "university", "rest", "description", "skill", "movexm3", "2017", "agile", "worked", "science", "java", "api", "june", "2016", "services", "using", "projects", "as400", "html", "monthscompany"],
    "SAP Developer": ["sap", "bo", "project", "hana", "reports", "data", "exprience", "business", "company", "months", "using", "developer", "users", "details", "description", "team", "application", "issues", "webi", "universe", "requirements", "worked", "bods", "client", "various", "environment", "views", "order", "working", "experience", "performance", "implemented", "user", "nestle", "activities", "involved", "design", "responsibilities", "maharashtra", "like"],
    "Sales": ["sales", "exprience", "months", "team", "details", "manager", "company", "description", "marketing", "ms", "year", "office", "college", "targets", "skill", "ltd", "cricket", "work", "staff", "worked", "skills", "managing", "clients", "leads", "less", "monthscompany", "working", "management", "performance", "school", "calling", "good", "lead", "university", "job", "knowledge", "bajaj", "month", "business", "maharashtra"],
    "Testing": ["testing", "test", "details", "exprience", "months", "maharashtra", "company", "check", "transformer", "january", "engineer", "description", "system", "project", "windows", "quality", "skill", "ltd", "android", "engineering", "per", "assembly", "electronics", "pvt", "application", "college", "resistance", "core", "pune", "management", "database", "work", "software", "ms", "name", "process", "transformers", "tests", "inspection", "good"],
    "Web Designing": ["project", "application", "description", "web", "exprience", "used", "bootstrap", "months", "details", "software", "company", "jquery", "developed", "technologies", "roles", "responsibility", "ui", "designed", "photoshop", "maharashtra", "website", "developer", "team", "php", "html5", "css3", "javascript", "nagpur", "trust", "time", "made", "loan", "database", "systems", "graphics", "ajax", "designer", "based", "pune", "html"]
}

# Create a dictionary to count the occurrences of each word
word_count = {}
for category, words in cv_categories.items():
    for word in words:
        if word in word_count:
            word_count[word] += 1
        else:
            word_count[word] = 1

# Find words that appear in more than one CV category
overlapping_words = [word for word, count in word_count.items() if count > 1]

# Print the overlapping words
print("Overlapping words among different CVs:")
print(overlapping_words)

unified_list = [
    'web', 'design', 'website', 'development', 'application', 'service', 'management', 'developer', 'designer', 'software', 
    'developed', 'site', 'marketing', 'business', 'html', 'content', 'state', 'cs', 'javascript', 'data', 'created', 'graphic', 
    'city', 'system', 'client', 'testing', 'test', 'patient', 'care', 'plan', 'procedure', 'information', 'student', 'tool', 
    'security', 'professional', 'staff', 'program', 'equipment', 'medical', 'sale', 'product', 'need', 'relationship', 'account', 
    'maintained', 'store', 'strategy', 'merchandise', 'communication', 'goal', 'revenue', 'inventory', 'market', 'area', 'current', 
    'sql', 'database', 'server', 'ssis', 'query', 'package', 'table', 'oracle', 'production', 'stored', 'solution', 'ssrs', 'tuning', 
    'implementation', 'abap', 'consultant', 'analysis', 'module', 'master', 'integration', 'configuration', 'react', 'spring', 
    'code', 'java', 'implemented', 'framework', 'python', 'aws', 'django', 'medium', 'public', 'relation', 'event', 'social', 
    'press', 'including', 'pr', 'community', 'campaign', 'pmo', 'operation', 'budget', 'resource', 'improvement', 'risk', 'change', 
    'leadership', 'financial', 'agile', 'employee', 'policy', 'daily', 'safety', 'operational', 'cost', 'member', 'network', 
    'cisco', 'firewall', 'engineer', 'switch', 'troubleshooting', 'router', 'infrastructure', 'access', 'hardware', 'device', 
    'routing', 'mechanical', 'engineering', 'manufacturing', 'maintenance', 'component', 'material', 'machine', 'part', 'solidworks', 
    'designed', 'specification', 'record', 'technology', 'computer', 'problem', 'hr', 'human', 'benefit', 'payroll', 'recruitment', 
    'compensation', 'department', 'compliance', 'fitness', 'health', 'exercise', 'group', 'personal', 'class', 'wellness', 'nutrition', 
    'trainer', 'certified', 'food', 'beverage', 'guest', 'restaurant', 'menu', 'standard', 'item', 'hotel', 'order', 'satisfaction', 
    'finance', 'accounting', 'tax', 'reconciliation', 'statement', 'prepared', 'audit', 'entry', 'payment', 'electrical', 'repair', 
    'wiring', 'circuit', 'installed', 'electrician', 'teacher', 'learning', 'classroom', 'lesson', 'teaching', 'educational', 
    'instruction', 'curriculum', 'positive', 'child', 'parent', 'behavior', 'etl', 'informatica', 'source', 'mapping', 'warehouse', 
    'file', 'net', 'aspnet', 'c', 'jquery', 'digital', 'brand', 'creative', 'google', 'devops', 'cloud', 'deployment', 'jenkins', 
    'docker', 'continuous', 'linux', 'azure', 'pipeline', 'git', 'automation', 'art', 'adobe', 'interior', 'recovery', 'administrator', 
    'monitoring', 'microsoft', 'science', 'model', 'research', 'year', 'scientist', 'civil', 'construction', 'building', 'water', 
    'analyst', 'stakeholder', 'use', 'diagram', 'worker', 'contractor', 'schedule', 'blockchain', 'faculty', 'contract', 'smart', 
    'york', 'banking', 'branch', 'loan', 'credit', 'cash', 'call', 'center', 'agent', 'aircraft', 'aviation', 'flight', 'pilot', 
    'personnel', 'vehicle', 'automotive', 'claim', 'director', 'english', 'language', 'grade', 'architect', 'architecture', 
    'architectural', 'planning', 'apparel', 'associate', 'display', 'organized', 'floor', 'merchandising', 'fashion', 'agricultural', 
    'farm', 'crop', 'agriculture', 'plant', 'advocate', 'legal', 'victim', 'family', 'provided'
]
['details', 'university', 'exprience', 'january', 'company', 'maharashtra', 'description', 'skill', 'less', 'year', 'months', 'mumbai', 'pune', 'college', 'cases', 'high', 'education', 'monthscompany', 'india', 'work', 'skills', 'civil', 'working', 'development', 'responsibilities', 'projects', 'experience', 'managing', 'new', 'marketing', 'management', 'nagpur', 'team', 'international', 'business', 'test', 'testing', 'automation', 'project', 'using', 'good', 'system', 'involved', 'software', 'environment', 'sql', 'knowledge', 'c', 'design', 'functional', 'web', 'python', 'documents', 'scripts', 'application', 'technology', 'computer', 'mysql', 'java', '2014', '2017', 'engineering', 'developer', 'worked', 'build', 'services', 'product', 'based', 'analytics', 'used', 'html', 'javascript', 'css', 'requirements', 'process', 'analysis', 'user', 'various', 'report', 'client', 'ltd', 'processes', 'pvt', 'maintain', 'documentation', 'ms', 'engineer', 'inspection', 'drawings', 'quality', 'name', 'etc', 'job', 'ensure', 'autocad', 'data', 'science', 'machine', 'like', 'sap', 'technical', 'hana', 'developed', 'database', 'server', 'oracle', 'backup', 'installation', 'servers', 'issues', 'support', 'windows', 'creating', 'linux', 'users', 'different', 'technologies', 'jquery', 'role', 'power', 'control', 'completed', 'per', 'activities', 'june', 'school', 'training', 'office', 'queries', 'sales', 'handling', 'customers', 'customer', 'manager', 'ajax', 'time', 'order', 'ãâ', 'operations', 'delivery', 'reports', 'performance']